# !/bin/sh

# set any system-dependent environment variables here
export POLYBAR="$XDG_CONFIG_HOME/polybar/config.ini" # path to the polybar loaded on startup
export POLYBAR_DPI=222 # Polybar DPI
export BAR_HEIGHT=45 # matched by polybar and dmenu

# icons sourced by lf at launch
. "$XDG_CONFIG_HOME/lf/icons.sh"

# source cargo environment at launch.
# Used for rust
. "$HOME/.local/share/cargo/env"

# source xprofile which launches all the programs 
. ~/.xprofile

# change pointer to mouse click
xsetroot -cursor_name left_ptr &

# starts bspwm, the default window manager
exec bspwm
